vich_uploader:
    db_driver: orm

    mappings:
        cat_picture:
            uri_prefix: /uploads/images/cats
            upload_destination: '%kernel.project_dir%/public/uploads/images/cats'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
